//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeshIO.Formats.Gltf.Schema.V2;
using System.Linq;
using System.Runtime.Serialization;


public class GltfSkin : IGltfNamedObject
{

	/// <summary>
	/// Backing field for InverseBindMatrices.
	/// </summary>
	private string _inverseBindMatrices;

	/// <summary>
	/// Backing field for Skeleton.
	/// </summary>
	private string _skeleton;

	/// <summary>
	/// Backing field for Joints.
	/// </summary>
	private int[] _joints;

	/// <summary>
	/// Backing field for Name.
	/// </summary>
	private string _name;

	/// <summary>
	/// Backing field for Extensions.
	/// </summary>
	private System.Collections.Generic.Dictionary<string, object> _extensions;

	/// <summary>
	/// Backing field for Extras.
	/// </summary>
	private GltfExtras _extras;

	/// <summary>
	/// The index of the accessor containing the floating-point 4x4 inverse-bind matrices.  The default is that each matrix is a 4x4 identity matrix, which implies that inverse-bind matrices were pre-applied.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("inverseBindMatrices")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("inverseBindMatrices")]
#endif
	public string InverseBindMatrices
	{
		get
		{
			return this._inverseBindMatrices;
		}
		set
		{
			this._inverseBindMatrices = value;
		}
	}

	/// <summary>
	/// The index of the node used as a skeleton root.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("skeleton")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("skeleton")]
#endif
	public string Skeleton
	{
		get
		{
			return this._skeleton;
		}
		set
		{
			this._skeleton = value;
		}
	}

	/// <summary>
	/// Indices of skeleton nodes, used as joints in this skin.
	/// </summary>
	//[Newtonsoft.Json.JsonRequiredAttribute()]
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("joints")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("joints")]
#endif
	public int[] Joints
	{
		get
		{
			return this._joints;
		}
		set
		{
			if ((value == null))
			{
				this._joints = value;
				return;
			}
			if ((value.Length < 1u))
			{
				throw new System.ArgumentException("Array not long enough");
			}
			int index = 0;
			for (index = 0; (index < value.Length); index = (index + 1))
			{
				if ((value[index] < 0))
				{
					throw new System.ArgumentOutOfRangeException();
				}
			}
			this._joints = value;
		}
	}

	/// <summary>
	/// The user-defined name of this object.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("name")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("name")]
#endif
	public string Name
	{
		get
		{
			return this._name;
		}
		set
		{
			this._name = value;
		}
	}

	/// <summary>
	/// Dictionary object with extension-specific objects.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("extensions")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("extensions")]
#endif
	public System.Collections.Generic.Dictionary<string, object> Extensions
	{
		get
		{
			return this._extensions;
		}
		set
		{
			this._extensions = value;
		}
	}

	/// <summary>
	/// Application-specific data.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("extras")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("extras")]
#endif
	public GltfExtras Extras
	{
		get
		{
			return this._extras;
		}
		set
		{
			this._extras = value;
		}
	}

	public bool ShouldSerializeInverseBindMatrices()
	{
		return ((_inverseBindMatrices == null)
					== false);
	}

	public bool ShouldSerializeSkeleton()
	{
		return ((_skeleton == null)
					== false);
	}

	public bool ShouldSerializeJoints()
	{
		return ((_joints == null)
					== false);
	}

	public bool ShouldSerializeName()
	{
		return ((_name == null)
					== false);
	}

	public bool ShouldSerializeExtensions()
	{
		return ((_extensions == null)
					== false);
	}

	public bool ShouldSerializeExtras()
	{
		return ((_extras == null)
					== false);
	}
}
