//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeshIO.Formats.Gltf.Schema.V2; 
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class GltfMaterialOcclusionTextureInfo {
        
        /// <summary>
        /// Backing field for Index.
        /// </summary>
        private int _index;
        
        /// <summary>
        /// Backing field for TexCoord.
        /// </summary>
        private int _texCoord = 0;
        
        /// <summary>
        /// Backing field for Strength.
        /// </summary>
        private float _strength = 1F;
        
        /// <summary>
        /// Backing field for Extensions.
        /// </summary>
        private System.Collections.Generic.Dictionary<string, object> _extensions;
        
        /// <summary>
        /// Backing field for Extras.
        /// </summary>
        private GltfExtras _extras;
        
        /// <summary>
        /// The index of the texture.
        /// </summary>
#if NET
#if NET7_0_OR_GREATER
        [System.Text.Json.Serialization.JsonRequired]
#endif
        [System.Text.Json.Serialization.JsonPropertyName("index")]
#else
        [Newtonsoft.Json.JsonRequiredAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("index")]
#endif
        public int Index {
            get {
                return this._index;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("Index", value, "Expected value to be greater than or equal to 0");
                }
                this._index = value;
            }
        }
        
        /// <summary>
        /// The set index of texture's TEXCOORD attribute used for texture coordinate mapping.
        /// </summary>
#if NET
        [System.Text.Json.Serialization.JsonPropertyName("texCoord")]
#else
        [Newtonsoft.Json.JsonPropertyAttribute("texCoord")]
#endif
        public int TexCoord {
            get {
                return this._texCoord;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("TexCoord", value, "Expected value to be greater than or equal to 0");
                }
                this._texCoord = value;
            }
        }
        
        /// <summary>
        /// A scalar multiplier controlling the amount of occlusion applied.
        /// </summary>
#if NET
        [System.Text.Json.Serialization.JsonPropertyName("strength")]
#else
        [Newtonsoft.Json.JsonPropertyAttribute("strength")]
#endif
        public float Strength {
            get {
                return this._strength;
            }
            set {
                if ((value < 0D)) {
                    throw new System.ArgumentOutOfRangeException("Strength", value, "Expected value to be greater than or equal to 0");
                }
                if ((value > 1D)) {
                    throw new System.ArgumentOutOfRangeException("Strength", value, "Expected value to be less than or equal to 1");
                }
                this._strength = value;
            }
        }
        
        /// <summary>
        /// Dictionary object with extension-specific objects.
        /// </summary>
#if NET
        [System.Text.Json.Serialization.JsonPropertyName("extensions")]
#else
        [Newtonsoft.Json.JsonPropertyAttribute("extensions")]
#endif
        public System.Collections.Generic.Dictionary<string, object> Extensions {
            get {
                return this._extensions;
            }
            set {
                this._extensions = value;
            }
        }
        
        /// <summary>
        /// Application-specific data.
        /// </summary>
#if NET
        [System.Text.Json.Serialization.JsonPropertyName("extras")]
#else
        [Newtonsoft.Json.JsonPropertyAttribute("extras")]
#endif
        public GltfExtras Extras {
            get {
                return this._extras;
            }
            set {
                this._extras = value;
            }
        }
        
        public bool ShouldSerializeTexCoord() {
            return ((_texCoord == 0) 
                        == false);
        }
        
        public bool ShouldSerializeStrength() {
            return ((_strength == 1F) 
                        == false);
        }
        
        public bool ShouldSerializeExtensions() {
            return ((_extensions == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtras() {
            return ((_extras == null) 
                        == false);
        }
    }
