//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeshIO.Formats.Gltf.Schema.V2;
using System.Linq;
using System.Runtime.Serialization;


public class GltfImage : IGltfNamedObject
{

	/// <summary>
	/// Backing field for Uri.
	/// </summary>
	private string _uri;

	/// <summary>
	/// Backing field for MimeType.
	/// </summary>
	private System.Nullable<MimeTypeEnum> _mimeType;

	/// <summary>
	/// Backing field for BufferView.
	/// </summary>
	private System.Nullable<int> _bufferView;

	/// <summary>
	/// Backing field for Name.
	/// </summary>
	private string _name;

	/// <summary>
	/// Backing field for Extensions.
	/// </summary>
	private System.Collections.Generic.Dictionary<string, object> _extensions;

	/// <summary>
	/// Backing field for Extras.
	/// </summary>
	private GltfExtras _extras;

	/// <summary>
	/// The uri of the image.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("uri")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("uri")]
#endif
	public string Uri
	{
		get
		{
			return this._uri;
		}
		set
		{
			this._uri = value;
		}
	}

	/// <summary>
	/// The image's MIME type. Required if `bufferView` is defined.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
	[System.Text.Json.Serialization.JsonPropertyName("mimeType")]
#else
	[Newtonsoft.Json.JsonConverterAttribute(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
	[Newtonsoft.Json.JsonPropertyAttribute("mimeType")]
#endif
	public System.Nullable<MimeTypeEnum> MimeType
	{
		get
		{
			return this._mimeType;
		}
		set
		{
			this._mimeType = value;
		}
	}

	/// <summary>
	/// The index of the bufferView that contains the image. Use this instead of the image's uri property.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("bufferView")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("bufferView")]
#endif
	public System.Nullable<int> BufferView
	{
		get
		{
			return this._bufferView;
		}
		set
		{
			if ((value < 0))
			{
				throw new System.ArgumentOutOfRangeException("BufferView", value, "Expected value to be greater than or equal to 0");
			}
			this._bufferView = value;
		}
	}

	/// <summary>
	/// The user-defined name of this object.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("name")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("name")]
#endif
	public string Name
	{
		get
		{
			return this._name;
		}
		set
		{
			this._name = value;
		}
	}

	/// <summary>
	/// Dictionary object with extension-specific objects.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("extensions")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("extensions")]
#endif
	public System.Collections.Generic.Dictionary<string, object> Extensions
	{
		get
		{
			return this._extensions;
		}
		set
		{
			this._extensions = value;
		}
	}

	/// <summary>
	/// Application-specific data.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("extras")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("extras")]
#endif
	public GltfExtras Extras
	{
		get
		{
			return this._extras;
		}
		set
		{
			this._extras = value;
		}
	}

	public bool ShouldSerializeUri()
	{
		return ((_uri == null)
					== false);
	}

	public bool ShouldSerializeMimeType()
	{
		return ((_mimeType == null)
					== false);
	}

	public bool ShouldSerializeBufferView()
	{
		return ((_bufferView == null)
					== false);
	}

	public bool ShouldSerializeName()
	{
		return ((_name == null)
					== false);
	}

	public bool ShouldSerializeExtensions()
	{
		return ((_extensions == null)
					== false);
	}

	public bool ShouldSerializeExtras()
	{
		return ((_extras == null)
					== false);
	}

	public enum MimeTypeEnum
	{

#if NET
		[System.Text.Json.Serialization.JsonPropertyName("image/jpeg")]
#else
		[EnumMember(Value = "image/jpeg")]
#endif
		image_jpeg,

#if NET
		[System.Text.Json.Serialization.JsonPropertyName("image/png")]
#else
		[EnumMember(Value = "image/png")]
#endif
		image_png,
	}
}
