//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeshIO.Formats.Gltf.Schema.V2;
using System.Linq;
using System.Runtime.Serialization;


public class GltfMesh : IGltfNamedObject
{

	/// <summary>
	/// Backing field for Primitives.
	/// </summary>
	private GltfMeshPrimitive[] _primitives;

	/// <summary>
	/// Backing field for Weights.
	/// </summary>
	private float[] _weights;

	/// <summary>
	/// Backing field for Name.
	/// </summary>
	private string _name;

	/// <summary>
	/// Backing field for Extensions.
	/// </summary>
	private System.Collections.Generic.Dictionary<string, object> _extensions;

	/// <summary>
	/// Backing field for Extras.
	/// </summary>
	private GltfExtras _extras;

	/// <summary>
	/// An array of primitives, each defining geometry to be rendered with a material.
	/// </summary>
#if NET
#if NET7_0_OR_GREATER
	[System.Text.Json.Serialization.JsonRequired]
#endif
	[System.Text.Json.Serialization.JsonPropertyName("primitives")]
#else
	[Newtonsoft.Json.JsonRequiredAttribute()]
	[Newtonsoft.Json.JsonPropertyAttribute("primitives")]
#endif
	public GltfMeshPrimitive[] Primitives
	{
		get
		{
			return this._primitives;
		}
		set
		{
			if ((value == null))
			{
				this._primitives = value;
				return;
			}
			if ((value.Length < 1u))
			{
				throw new System.ArgumentException("Array not long enough");
			}
			this._primitives = value;
		}
	}

	/// <summary>
	/// Array of weights to be applied to the Morph Targets.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("weights")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("weights")]
#endif
	public float[] Weights
	{
		get
		{
			return this._weights;
		}
		set
		{
			if ((value == null))
			{
				this._weights = value;
				return;
			}
			if ((value.Length < 1u))
			{
				throw new System.ArgumentException("Array not long enough");
			}
			this._weights = value;
		}
	}

	/// <summary>
	/// The user-defined name of this object.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("name")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("name")]
#endif
	public string Name
	{
		get
		{
			return this._name;
		}
		set
		{
			this._name = value;
		}
	}

	/// <summary>
	/// Dictionary object with extension-specific objects.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("extensions")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("extensions")]
#endif
	public System.Collections.Generic.Dictionary<string, object> Extensions
	{
		get
		{
			return this._extensions;
		}
		set
		{
			this._extensions = value;
		}
	}

	/// <summary>
	/// Application-specific data.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("extras")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("extras")]
#endif
	public GltfExtras Extras
	{
		get
		{
			return this._extras;
		}
		set
		{
			this._extras = value;
		}
	}

	public bool ShouldSerializePrimitives()
	{
		return ((_primitives == null)
					== false);
	}

	public bool ShouldSerializeWeights()
	{
		return ((_weights == null)
					== false);
	}

	public bool ShouldSerializeName()
	{
		return ((_name == null)
					== false);
	}

	public bool ShouldSerializeExtensions()
	{
		return ((_extensions == null)
					== false);
	}

	public bool ShouldSerializeExtras()
	{
		return ((_extras == null)
					== false);
	}
}
