//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeshIO.Formats.Gltf.Schema.V2;
using System.Linq;
using System.Runtime.Serialization;


public class GltfBuffer : IGltfNamedObject
{

	/// <summary>
	/// Backing field for Uri.
	/// </summary>
	private string _uri;

	/// <summary>
	/// Backing field for ByteLength.
	/// </summary>
	private int _byteLength;

	/// <summary>
	/// Backing field for Name.
	/// </summary>
	private string _name;

	/// <summary>
	/// Backing field for Extensions.
	/// </summary>
	private System.Collections.Generic.Dictionary<string, object> _extensions;

	/// <summary>
	/// Backing field for Extras.
	/// </summary>
	private GltfExtras _extras;

	/// <summary>
	/// The uri of the buffer.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("uri")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("uri")]
#endif
	public string Uri
	{
		get
		{
			return this._uri;
		}
		set
		{
			this._uri = value;
		}
	}

	/// <summary>
	/// The length of the buffer in bytes.
	/// </summary>
#if NET
#if NET7_0_OR_GREATER
	[System.Text.Json.Serialization.JsonRequired]
#endif
	[System.Text.Json.Serialization.JsonPropertyName("byteLength")]
#else
	[Newtonsoft.Json.JsonRequiredAttribute()]
	[Newtonsoft.Json.JsonPropertyAttribute("byteLength")]
#endif
	public int ByteLength
	{
		get
		{
			return this._byteLength;
		}
		set
		{
			if ((value < 1))
			{
				throw new System.ArgumentOutOfRangeException("ByteLength", value, "Expected value to be greater than or equal to 1");
			}
			this._byteLength = value;
		}
	}

	/// <summary>
	/// The user-defined name of this object.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("name")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("name")]
#endif
	public string Name
	{
		get
		{
			return this._name;
		}
		set
		{
			this._name = value;
		}
	}

	/// <summary>
	/// Dictionary object with extension-specific objects.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("extensions")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("extensions")]
#endif
	public System.Collections.Generic.Dictionary<string, object> Extensions
	{
		get
		{
			return this._extensions;
		}
		set
		{
			this._extensions = value;
		}
	}

	/// <summary>
	/// Application-specific data.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("extras")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("extras")]
#endif
	public GltfExtras Extras
	{
		get
		{
			return this._extras;
		}
		set
		{
			this._extras = value;
		}
	}

	public bool ShouldSerializeUri()
	{
		return ((_uri == null)
					== false);
	}

	public bool ShouldSerializeName()
	{
		return ((_name == null)
					== false);
	}

	public bool ShouldSerializeExtensions()
	{
		return ((_extensions == null)
					== false);
	}

	public bool ShouldSerializeExtras()
	{
		return ((_extras == null)
					== false);
	}
}
