//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeshIO.Formats.Gltf.Schema.V2;
using System.Linq;
using System.Runtime.Serialization;


public class GltfTexture : IGltfNamedObject
{

	/// <summary>
	/// Backing field for Sampler.
	/// </summary>
	private string _sampler;

	/// <summary>
	/// Backing field for Source.
	/// </summary>
	private string _source;

	/// <summary>
	/// Backing field for Name.
	/// </summary>
	private string _name;

	/// <summary>
	/// Backing field for Extensions.
	/// </summary>
	private System.Collections.Generic.Dictionary<string, object> _extensions;

	/// <summary>
	/// Backing field for Extras.
	/// </summary>
	private GltfExtras _extras;

	/// <summary>
	/// The index of the sampler used by this texture. When undefined, a sampler with repeat wrapping and auto filtering should be used.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("sampler")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("sampler")]
#endif
	public string Sampler
	{
		get
		{
			return this._sampler;
		}
		set
		{
			this._sampler = value;
		}
	}

	/// <summary>
	/// The index of the image used by this texture. When undefined, it is expected that an extension or other mechanism will supply an alternate texture source, otherwise behavior is undefined.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("source")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("source")]
#endif
	public string Source
	{
		get
		{
			return this._source;
		}
		set
		{
			this._source = value;
		}
	}

	/// <summary>
	/// The user-defined name of this object.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("name")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("name")]
#endif
	public string Name
	{
		get
		{
			return this._name;
		}
		set
		{
			this._name = value;
		}
	}

	/// <summary>
	/// Dictionary object with extension-specific objects.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("extensions")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("extensions")]
#endif
	public System.Collections.Generic.Dictionary<string, object> Extensions
	{
		get
		{
			return this._extensions;
		}
		set
		{
			this._extensions = value;
		}
	}

	/// <summary>
	/// Application-specific data.
	/// </summary>
#if NET
	[System.Text.Json.Serialization.JsonPropertyName("extras")]
#else
	[Newtonsoft.Json.JsonPropertyAttribute("extras")]
#endif
	public GltfExtras Extras
	{
		get
		{
			return this._extras;
		}
		set
		{
			this._extras = value;
		}
	}

	public bool ShouldSerializeSampler()
	{
		return ((_sampler == null)
					== false);
	}

	public bool ShouldSerializeSource()
	{
		return ((_source == null)
					== false);
	}

	public bool ShouldSerializeName()
	{
		return ((_name == null)
					== false);
	}

	public bool ShouldSerializeExtensions()
	{
		return ((_extensions == null)
					== false);
	}

	public bool ShouldSerializeExtras()
	{
		return ((_extras == null)
					== false);
	}
}
