//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeshIO.GLTF.Schema.V2 {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class GltfMaterial {
        
        /// <summary>
        /// Backing field for Name.
        /// </summary>
        private string _name;
        
        /// <summary>
        /// Backing field for Extensions.
        /// </summary>
        private System.Collections.Generic.Dictionary<string, object> _extensions;
        
        /// <summary>
        /// Backing field for Extras.
        /// </summary>
        private GltfExtras _extras;
        
        /// <summary>
        /// Backing field for PbrMetallicRoughness.
        /// </summary>
        private GltfMaterialPbrMetallicRoughness _pbrMetallicRoughness;
        
        /// <summary>
        /// Backing field for NormalTexture.
        /// </summary>
        private GltfMaterialNormalTextureInfo _normalTexture;
        
        /// <summary>
        /// Backing field for OcclusionTexture.
        /// </summary>
        private GltfMaterialOcclusionTextureInfo _occlusionTexture;
        
        /// <summary>
        /// Backing field for EmissiveTexture.
        /// </summary>
        private GltfTextureInfo _emissiveTexture;
        
        /// <summary>
        /// Backing field for EmissiveFactor.
        /// </summary>
        private float[] _emissiveFactor = new float[] {
                0F,
                0F,
                0F};
        
        /// <summary>
        /// Backing field for AlphaMode.
        /// </summary>
        private AlphaModeEnum _alphaMode = AlphaModeEnum.OPAQUE;
        
        /// <summary>
        /// Backing field for AlphaCutoff.
        /// </summary>
        private float _alphaCutoff = 0.5F;
        
        /// <summary>
        /// Backing field for DoubleSided.
        /// </summary>
        private bool _doubleSided = false;
        
        /// <summary>
        /// The user-defined name of this object.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("name")]
        public string Name {
            get {
                return this._name;
            }
            set {
                this._name = value;
            }
        }
        
        /// <summary>
        /// Dictionary object with extension-specific objects.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("extensions")]
        public System.Collections.Generic.Dictionary<string, object> Extensions {
            get {
                return this._extensions;
            }
            set {
                this._extensions = value;
            }
        }
        
        /// <summary>
        /// Application-specific data.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("extras")]
        public GltfExtras Extras {
            get {
                return this._extras;
            }
            set {
                this._extras = value;
            }
        }
        
        /// <summary>
        /// A set of parameter values that are used to define the metallic-roughness material model from Physically-Based Rendering (PBR) methodology. When not specified, all the default values of `pbrMetallicRoughness` apply.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("pbrMetallicRoughness")]
        public GltfMaterialPbrMetallicRoughness PbrMetallicRoughness {
            get {
                return this._pbrMetallicRoughness;
            }
            set {
                this._pbrMetallicRoughness = value;
            }
        }
        
        /// <summary>
        /// The normal map texture.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("normalTexture")]
        public GltfMaterialNormalTextureInfo NormalTexture {
            get {
                return this._normalTexture;
            }
            set {
                this._normalTexture = value;
            }
        }
        
        /// <summary>
        /// The occlusion map texture.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("occlusionTexture")]
        public GltfMaterialOcclusionTextureInfo OcclusionTexture {
            get {
                return this._occlusionTexture;
            }
            set {
                this._occlusionTexture = value;
            }
        }
        
        /// <summary>
        /// The emissive map texture.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("emissiveTexture")]
        public GltfTextureInfo EmissiveTexture {
            get {
                return this._emissiveTexture;
            }
            set {
                this._emissiveTexture = value;
            }
        }
        
        /// <summary>
        /// The emissive color of the material.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("emissiveFactor")]
        public float[] EmissiveFactor {
            get {
                return this._emissiveFactor;
            }
            set {
                if ((value.Length < 3u)) {
                    throw new System.ArgumentException("Array not long enough");
                }
                if ((value.Length > 3u)) {
                    throw new System.ArgumentException("Array too long");
                }
                int index = 0;
                for (index = 0; (index < value.Length); index = (index + 1)) {
                    if ((value[index] < 0D)) {
                        throw new System.ArgumentOutOfRangeException();
                    }
                }
                for (index = 0; (index < value.Length); index = (index + 1)) {
                    if ((value[index] > 1D)) {
                        throw new System.ArgumentOutOfRangeException();
                    }
                }
                this._emissiveFactor = value;
            }
        }
        
        /// <summary>
        /// The alpha rendering mode of the material.
        /// </summary>
        [Newtonsoft.Json.JsonConverterAttribute(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [Newtonsoft.Json.JsonPropertyAttribute("alphaMode")]
        public AlphaModeEnum AlphaMode {
            get {
                return this._alphaMode;
            }
            set {
                this._alphaMode = value;
            }
        }
        
        /// <summary>
        /// The alpha cutoff value of the material.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("alphaCutoff")]
        public float AlphaCutoff {
            get {
                return this._alphaCutoff;
            }
            set {
                if ((value < 0D)) {
                    throw new System.ArgumentOutOfRangeException("AlphaCutoff", value, "Expected value to be greater than or equal to 0");
                }
                this._alphaCutoff = value;
            }
        }
        
        /// <summary>
        /// Specifies whether the material is double sided.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("doubleSided")]
        public bool DoubleSided {
            get {
                return this._doubleSided;
            }
            set {
                this._doubleSided = value;
            }
        }
        
        public bool ShouldSerializeName() {
            return ((_name == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtensions() {
            return ((_extensions == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtras() {
            return ((_extras == null) 
                        == false);
        }
        
        public bool ShouldSerializePbrMetallicRoughness() {
            return ((_pbrMetallicRoughness == null) 
                        == false);
        }
        
        public bool ShouldSerializeNormalTexture() {
            return ((_normalTexture == null) 
                        == false);
        }
        
        public bool ShouldSerializeOcclusionTexture() {
            return ((_occlusionTexture == null) 
                        == false);
        }
        
        public bool ShouldSerializeEmissiveTexture() {
            return ((_emissiveTexture == null) 
                        == false);
        }
        
        public bool ShouldSerializeEmissiveFactor() {
            return (_emissiveFactor.SequenceEqual(new float[] {
                        0F,
                        0F,
                        0F}) == false);
        }
        
        public bool ShouldSerializeAlphaMode() {
            return ((_alphaMode == AlphaModeEnum.OPAQUE) 
                        == false);
        }
        
        public bool ShouldSerializeAlphaCutoff() {
            return ((_alphaCutoff == 0.5F) 
                        == false);
        }
        
        public bool ShouldSerializeDoubleSided() {
            return ((_doubleSided == false) 
                        == false);
        }
        
        public enum AlphaModeEnum {
            
            OPAQUE,
            
            MASK,
            
            BLEND,
        }
    }
}
