//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeshIO.GLTF.Schema.V2 {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class GltfAsset {
        
        /// <summary>
        /// Backing field for Copyright.
        /// </summary>
        private string _copyright;
        
        /// <summary>
        /// Backing field for Generator.
        /// </summary>
        private string _generator;
        
        /// <summary>
        /// Backing field for Version.
        /// </summary>
        private string _version;
        
        /// <summary>
        /// Backing field for MinVersion.
        /// </summary>
        private string _minVersion;
        
        /// <summary>
        /// Backing field for Extensions.
        /// </summary>
        private System.Collections.Generic.Dictionary<string, object> _extensions;
        
        /// <summary>
        /// Backing field for Extras.
        /// </summary>
        private GltfExtras _extras;
        
        /// <summary>
        /// A copyright message suitable for display to credit the content creator.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("copyright")]
        public string Copyright {
            get {
                return this._copyright;
            }
            set {
                this._copyright = value;
            }
        }
        
        /// <summary>
        /// Tool that generated this glTF model.  Useful for debugging.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("generator")]
        public string Generator {
            get {
                return this._generator;
            }
            set {
                this._generator = value;
            }
        }
        
        /// <summary>
        /// The glTF version that this asset targets.
        /// </summary>
        [Newtonsoft.Json.JsonRequiredAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("version")]
        public string Version {
            get {
                return this._version;
            }
            set {
                this._version = value;
            }
        }
        
        /// <summary>
        /// The minimum glTF version that this asset targets.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("minVersion")]
        public string MinVersion {
            get {
                return this._minVersion;
            }
            set {
                this._minVersion = value;
            }
        }
        
        /// <summary>
        /// Dictionary object with extension-specific objects.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("extensions")]
        public System.Collections.Generic.Dictionary<string, object> Extensions {
            get {
                return this._extensions;
            }
            set {
                this._extensions = value;
            }
        }
        
        /// <summary>
        /// Application-specific data.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("extras")]
        public GltfExtras Extras {
            get {
                return this._extras;
            }
            set {
                this._extras = value;
            }
        }
        
        public bool ShouldSerializeCopyright() {
            return ((_copyright == null) 
                        == false);
        }
        
        public bool ShouldSerializeGenerator() {
            return ((_generator == null) 
                        == false);
        }
        
        public bool ShouldSerializeVersion() {
            return ((_version == null) 
                        == false);
        }
        
        public bool ShouldSerializeMinVersion() {
            return ((_minVersion == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtensions() {
            return ((_extensions == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtras() {
            return ((_extras == null) 
                        == false);
        }
    }
}
