//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeshIO.GLTF.Schema.V2 {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class GltfNode {
        
        /// <summary>
        /// Backing field for Camera.
        /// </summary>
        private System.Nullable<int> _camera;
        
        /// <summary>
        /// Backing field for Children.
        /// </summary>
        private int[] _children;
        
        /// <summary>
        /// Backing field for Skin.
        /// </summary>
        private System.Nullable<int> _skin;
        
        /// <summary>
        /// Backing field for Matrix.
        /// </summary>
        private float[] _matrix = new float[] {
                1F,
                0F,
                0F,
                0F,
                0F,
                1F,
                0F,
                0F,
                0F,
                0F,
                1F,
                0F,
                0F,
                0F,
                0F,
                1F};
        
        /// <summary>
        /// Backing field for Mesh.
        /// </summary>
        private System.Nullable<int> _mesh;
        
        /// <summary>
        /// Backing field for Rotation.
        /// </summary>
        private float[] _rotation = new float[] {
                0F,
                0F,
                0F,
                1F};
        
        /// <summary>
        /// Backing field for Scale.
        /// </summary>
        private float[] _scale = new float[] {
                1F,
                1F,
                1F};
        
        /// <summary>
        /// Backing field for Translation.
        /// </summary>
        private float[] _translation = new float[] {
                0F,
                0F,
                0F};
        
        /// <summary>
        /// Backing field for Weights.
        /// </summary>
        private float[] _weights;
        
        /// <summary>
        /// Backing field for Name.
        /// </summary>
        private string _name;
        
        /// <summary>
        /// Backing field for Extensions.
        /// </summary>
        private System.Collections.Generic.Dictionary<string, object> _extensions;
        
        /// <summary>
        /// Backing field for Extras.
        /// </summary>
        private GltfExtras _extras;
        
        /// <summary>
        /// The index of the camera referenced by this node.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("camera")]
        public System.Nullable<int> Camera {
            get {
                return this._camera;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("Camera", value, "Expected value to be greater than or equal to 0");
                }
                this._camera = value;
            }
        }
        
        /// <summary>
        /// The indices of this node's children.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("children")]
        public int[] Children {
            get {
                return this._children;
            }
            set {
                if ((value == null)) {
                    this._children = value;
                    return;
                }
                if ((value.Length < 1u)) {
                    throw new System.ArgumentException("Array not long enough");
                }
                int index = 0;
                for (index = 0; (index < value.Length); index = (index + 1)) {
                    if ((value[index] < 0)) {
                        throw new System.ArgumentOutOfRangeException();
                    }
                }
                this._children = value;
            }
        }
        
        /// <summary>
        /// The index of the skin referenced by this node.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("skin")]
        public System.Nullable<int> Skin {
            get {
                return this._skin;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("Skin", value, "Expected value to be greater than or equal to 0");
                }
                this._skin = value;
            }
        }
        
        /// <summary>
        /// A floating-point 4x4 transformation matrix stored in column-major order.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("matrix")]
        public float[] Matrix {
            get {
                return this._matrix;
            }
            set {
                if ((value.Length < 16u)) {
                    throw new System.ArgumentException("Array not long enough");
                }
                if ((value.Length > 16u)) {
                    throw new System.ArgumentException("Array too long");
                }
                this._matrix = value;
            }
        }
        
        /// <summary>
        /// The index of the mesh in this node.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("mesh")]
        public System.Nullable<int> Mesh {
            get {
                return this._mesh;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("Mesh", value, "Expected value to be greater than or equal to 0");
                }
                this._mesh = value;
            }
        }
        
        /// <summary>
        /// The node's unit quaternion rotation in the order (x, y, z, w), where w is the scalar.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("rotation")]
        public float[] Rotation {
            get {
                return this._rotation;
            }
            set {
                if ((value.Length < 4u)) {
                    throw new System.ArgumentException("Array not long enough");
                }
                if ((value.Length > 4u)) {
                    throw new System.ArgumentException("Array too long");
                }
                int index = 0;
                for (index = 0; (index < value.Length); index = (index + 1)) {
                    if ((value[index] < -1D)) {
                        throw new System.ArgumentOutOfRangeException();
                    }
                }
                for (index = 0; (index < value.Length); index = (index + 1)) {
                    if ((value[index] > 1D)) {
                        throw new System.ArgumentOutOfRangeException();
                    }
                }
                this._rotation = value;
            }
        }
        
        /// <summary>
        /// The node's non-uniform scale, given as the scaling factors along the x, y, and z axes.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("scale")]
        public float[] Scale {
            get {
                return this._scale;
            }
            set {
                if ((value.Length < 3u)) {
                    throw new System.ArgumentException("Array not long enough");
                }
                if ((value.Length > 3u)) {
                    throw new System.ArgumentException("Array too long");
                }
                this._scale = value;
            }
        }
        
        /// <summary>
        /// The node's translation along the x, y, and z axes.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("translation")]
        public float[] Translation {
            get {
                return this._translation;
            }
            set {
                if ((value.Length < 3u)) {
                    throw new System.ArgumentException("Array not long enough");
                }
                if ((value.Length > 3u)) {
                    throw new System.ArgumentException("Array too long");
                }
                this._translation = value;
            }
        }
        
        /// <summary>
        /// The weights of the instantiated Morph Target. Number of elements must match number of Morph Targets of used mesh.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("weights")]
        public float[] Weights {
            get {
                return this._weights;
            }
            set {
                if ((value == null)) {
                    this._weights = value;
                    return;
                }
                if ((value.Length < 1u)) {
                    throw new System.ArgumentException("Array not long enough");
                }
                this._weights = value;
            }
        }
        
        /// <summary>
        /// The user-defined name of this object.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("name")]
        public string Name {
            get {
                return this._name;
            }
            set {
                this._name = value;
            }
        }
        
        /// <summary>
        /// Dictionary object with extension-specific objects.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("extensions")]
        public System.Collections.Generic.Dictionary<string, object> Extensions {
            get {
                return this._extensions;
            }
            set {
                this._extensions = value;
            }
        }
        
        /// <summary>
        /// Application-specific data.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("extras")]
        public GltfExtras Extras {
            get {
                return this._extras;
            }
            set {
                this._extras = value;
            }
        }
        
        public bool ShouldSerializeCamera() {
            return ((_camera == null) 
                        == false);
        }
        
        public bool ShouldSerializeChildren() {
            return ((_children == null) 
                        == false);
        }
        
        public bool ShouldSerializeSkin() {
            return ((_skin == null) 
                        == false);
        }
        
        public bool ShouldSerializeMatrix() {
            return (_matrix.SequenceEqual(new float[] {
                        1F,
                        0F,
                        0F,
                        0F,
                        0F,
                        1F,
                        0F,
                        0F,
                        0F,
                        0F,
                        1F,
                        0F,
                        0F,
                        0F,
                        0F,
                        1F}) == false);
        }
        
        public bool ShouldSerializeMesh() {
            return ((_mesh == null) 
                        == false);
        }
        
        public bool ShouldSerializeRotation() {
            return (_rotation.SequenceEqual(new float[] {
                        0F,
                        0F,
                        0F,
                        1F}) == false);
        }
        
        public bool ShouldSerializeScale() {
            return (_scale.SequenceEqual(new float[] {
                        1F,
                        1F,
                        1F}) == false);
        }
        
        public bool ShouldSerializeTranslation() {
            return (_translation.SequenceEqual(new float[] {
                        0F,
                        0F,
                        0F}) == false);
        }
        
        public bool ShouldSerializeWeights() {
            return ((_weights == null) 
                        == false);
        }
        
        public bool ShouldSerializeName() {
            return ((_name == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtensions() {
            return ((_extensions == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtras() {
            return ((_extras == null) 
                        == false);
        }
    }
}
